import React, { useState } from 'react';
import { Check, Copy, Sparkles } from 'lucide-react';

interface FinalAnswerViewProps {
  finalAnswer: string;
  runId: string;
  createdAt: string;
}

export const FinalAnswerView: React.FC<FinalAnswerViewProps> = ({
  finalAnswer,
  runId,
  createdAt,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(finalAnswer);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section className="glass-panel final-answer-panel">
      <div className="final-answer-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
          <Sparkles size={20} color="var(--accent-primary)" />
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700 }}>
            Final Synthesized Response
          </h2>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <span style={{ fontSize: '0.75rem', fontFamily: 'var(--font-mono)', color: 'var(--text-muted)' }}>
            Run ID: {runId.slice(0, 8)}...
          </span>
          <button type="button" className="copy-btn" onClick={handleCopy}>
            {copied ? (
              <>
                <Check size={14} color="var(--accent-emerald)" />
                Copied!
              </>
            ) : (
              <>
                <Copy size={14} />
                Copy Response
              </>
            )}
          </button>
        </div>
      </div>

      <div className="prose-content" style={{ fontSize: '1rem', lineHeight: '1.8' }}>
        {finalAnswer}
      </div>

      <div style={{ marginTop: '1.5rem', paddingTop: '1rem', borderTop: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', fontSize: '0.78rem', color: 'var(--text-muted)' }}>
        <span>Generated by Synthesizer Agent</span>
        <span>Timestamp: {new Date(createdAt).toLocaleString()}</span>
      </div>
    </section>
  );
};
