"""
Real End-to-End PDF RAG Integration Test against live running backend server.
"""

import httpx

def test_real_pdf_rag_end_to_end():
    pdf_text = (
        "ELECTRIC AND PETROL VEHICLES COMPREHENSIVE REPORT\n\n"
        "1. Lifecycle Emissions:\n"
        "Electric vehicles (EVs) generate approximately 50-70% lower lifecycle greenhouse gas emissions "
        "compared to internal combustion engine (ICE) petrol vehicles over a 150,000 km operational lifetime. "
        "Battery manufacturing accounts for 40% of EV embodied carbon, but clean grid charging offsets this within 1.5 years of driving.\n\n"
        "2. Total Cost of Ownership (TCO):\n"
        "While initial purchase price for EVs remains 15-25% higher, operating costs are 60% lower per kilometer. "
        "Over a 5-year ownership period at 20,000 km/year, EV TCO reaches parity or savings compared to petrol cars.\n\n"
        "3. Infrastructure Requirements:\n"
        "EV adoption requires accessible Level 2 home/workplace charging and Ultra-Fast DC fast chargers along highways. "
        "Petrol infrastructure relies on existing global liquid refueling stations with 5-minute fueling times.\n\n"
        "4. Long-Term Adoption:\n"
        "Global EV market share is projected to reach 60% of new passenger vehicle sales by 2030, driven by battery cost declines below $100/kWh."
    )

    doc_payload = {
        "filename": "EV_vs_Petrol_Lifecycle_Report.pdf",
        "content": pdf_text,
    }

    request_payload = {
        "task": "Compare electric and petrol vehicles across lifecycle emissions, total cost of ownership, infrastructure requirements, and long-term adoption.",
        "documents": [doc_payload],
    }

    print("Sending live API request to http://localhost:8000/api/run ...")
    response = httpx.post("http://localhost:8000/api/run", json=request_payload, timeout=120.0)

    print("HTTP Status Code:", response.status_code)
    assert response.status_code == 200, f"Error: {response.text}"

    data = response.json()
    print("Run ID:", data["run_id"])
    print("Subtasks generated by Planner:")
    for t in data["subtasks"]:
        retrieval_q = t.get("metadata", {}).get("retrieval_query") if t.get("metadata") else None
        print(f"  - [{t['id']}] ({t['type']}) {t['description']} | retrieval_query: {retrieval_q}")

    print(f"\nRetrieved Chunks Count: {len(data['retrieved_chunks'])}")
    for i, chunk in enumerate(data["retrieved_chunks"]):
        print(f"\nChunk {i+1} [Doc: {chunk.get('document_id')} | Source: {chunk.get('source')} | Score: {chunk.get('similarity_score', 0):.2f}]:")
        print("  Content snippet:", chunk.get("content", "")[:120], "...")

    print("\nFinal Answer Snippet:")
    print(data["final_answer"][:400], "...")

    # Assertions
    assert len(data["subtasks"]) >= 3
    assert len(data["retrieved_chunks"]) >= 1
    print("\n>>> REAL END-TO-END PDF RAG TEST PASSED SUCCESSFULLY! <<<")

if __name__ == "__main__":
    test_real_pdf_rag_end_to_end()
